### ISSUE TITLE
NO ADS

### ISSUE THREAD

**Issue by chumuye** [qinyuhang/ShadowsocksX-NG-R#56]
NO ADS.

**Comment by chumuye** [comment]
东西不贵，省去到处找账号的麻烦，省下的时间就是金钱！
 👍 1 ❤️ 1

**Comment by liangtb** [comment]
别在这里做广告好吗，发一下就行了


On 1 December 2017 at 12:03:42 PM, chumuye (notifications@github.com) wrote:

东西不贵，省去到处找账号的麻烦，省下的时间就是金钱！
👍 1 ❤️ 1

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/qinyuhang/ShadowsocksX-NG-R/issues/56#issuecomment-348395705>,
or mute the thread
