### ISSUE TITLE
1.4.3 版本链接不上服务器

### ISSUE THREAD

**Issue by MunMunMiao** [qinyuhang/ShadowsocksX-NG-R#6]
![sadasdasd](https://user-images.githubusercontent.com/18216142/29737842-419ccbb8-8a48-11e7-80a4-1d084f43d07c.jpeg)
情况和log在图片里

window版本的没问题。链接地址改域名和ip都不行

**Comment by ghost** [comment]
Seems like your proxy app runs with "Manual Mode". 
With this mode, this app will not modify the system proxy setting, but still leaves ss-local running in the background, so that you can use Shadowsocks by configurating manually in other apps, such as Proxy SwitchyOmega.

So change the mode to "Auto Mode by PAC" or "ACL Auto" may helps you.

**Comment by MunMunMiao** [comment]
@macron77 I can only operate normally in Manual Mode mode. If it's using Manual Mode and Global Mode, there's no problem. But the other mode, the server will occasionally appear not connected, whether it is IP or domain name.

**Comment by ghost** [comment]
@wunonglin Seems like the app can't modify the system proxy setting correctly. 
Try running 
`sudo bash /Applications/ShadowsocksX-NG-R8.app/Contents/Resources/install_helper.sh` to reinstall  the helper, which is used to modify system settings.

Have you checked the proxy setting while using 'Auto Mode by PAC'? The "Auto Proxy Configuration" box should be checked(☑️).

**Comment by MunMunMiao** [comment]
@macron77 OK, I'm running, and there's no obvious error. Tks
